lrn_temp/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    url('relative/',views.relative,name='relative'),
    url('other/',views.other,name='other'),
]

lrn_temp/lrn_temp/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include,url

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls'))
]

lrn_temp/basic_app/models.py
from django.db import models

# Create your models here.

lrn_temp/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'Hello,World!','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url.html')

lrn_temp/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-expand-lg navbar-light bg-light navbar-static-top'>
      <div class="container">
        <ul class = "navbar-nav">
          <li><a class ='navbar-brand' href="{% url 'index' %}">BRAND</a></li>
          <li><a class ='navbar-brand' href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class ='navbar-brand' href="{% url 'basic_app:other' %}">Other</a></li>
          <li><a class ='navbar-brand' href="{% url 'basic_app:relative' %}">Relative</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

lrn_temp/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_extras %}
  {% block body_block %}
    <h1>WELCOME TO INDEX PAGE</h1>
    <h2>This is an Index Page</h2>
    {{ text|cut:'hello' }}
    {{ number|add:'5' }}
    {% endblock %}

lrn_temp/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHERS</h1>
    <h2>This is an example for template inheritance</h2>
    {% endblock %}

lrn_temp/templates/basic_app/relative_url.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>WELCOME TO RELATIVE URL PAGE</h1>
    <a class ='link-secondary' href="{% url 'basic_app:other' %}">OTHER PAGE</a>
    {% endblock %}